### PR TITLE
Add support for custom functions

### LINKED ISSUE #37: Standardize function signatures and add "registry"
I'd like to allow users to add their own functions. The main use case right now is the tetramer validator, where we want to be able to check modification types and positions against a sequence:

MHC Molecule | Peptide Sequence | Modification Type | Modification Position
-- | -- | -- | --
HLA-A*02:01 | PKYVKQNTLKLAT | OX | M5
HLA-A*02:01 | NLVPMVATV | oxidation | M5

To make this possible, I think we need a few changes to VALVE:

1. Make all the functions use the same signature. It will have to include anything a function could need. My suggestion is: config dict, args list, table string, column string, row int. This should be enough to look up the current cell, but also get information from other cells in the row if needed. All functions should return a list of messages, which will be empty if the cell is valid.
2. Extend the config with a dictionary of function name -> function pairs. Users will be able to add to this dictionary. I guess this needs to be specified before the datatype, field, and rule tables are checked. I'm thinking that an unknown function should be a WARN (and then skipped), which would allow you to use a function in Python that's not defined for JavaScript. But maybe it should be an ERROR.
3. In [run_function](https://github.com/ontodev/valve.py/blob/main/valve/valve.py#L972) look for the function name in the dictionary from 2 and call the function with the standard arguments from 1.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #37 

### Custom Functions

You may call `valve.validate` with an optional `functions={...}` argument. The dictionary value should be in the format of function name (for use in rule and field tables) -> function object (which may or may not have the same name). The function name should not collide with any [builtin functions](https://github.com/ontodev/valve/blob/main/README.md#functions). The function must be defined in your file with the following required parameters in this order, even if they are not all used:

1. `config`: VALVE configuration dictionary
2. `args`: parsed (via `valve.parse`) arguments from the function
3. `table`: table name containing value
4. `column`: column name containing value
5. `row_idx`: row index containing value
6. `value`: value to run the function on

The function should return a list of messages (empty on success). The messages are dictionaries with the following keys:
* `table`: table name (no parent directories or extension)
* `cell`: A1 format of cell location (you can use `idx_to_a1` to get this\*)
* `message`: detailed error message

\* When getting the A1 format of the location, note that the `row_idx` always starts at zero, without headers (or any skipped rows) included in the list of rows. You must add `row_start` to this to get the correct row number.

You may also include a `suggestion` key if you want to provide a suggested replacement value.

For example:
```python
def foo_bar(config, args, table, column, row_idx, value):
    required_in_value = args[0]["value"]
    if required_in_value not in value:
        row_start = config["row_start"]
        col_idx = config["table_details"][table]["fields"].index(column)
        cell_loc = valve.idx_to_a1(row_idx + row_start, col_idx + 1)
        return [
            {
                "table": table,
                "cell": cell_loc,
                "message": f"'{value}' must contain '{required_in_value}'",
            }
        ]
    return []

valve.validate("inputs/", functions={"foo": foo_bar})
```

### CODE REVIEW

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
This is mostly right, but not as flexible as what I asked for in #37:

1. `lookup_value` isn't enough. I want functions to be able to look anywhere, which is why I asked for `table, column, row` coordinates to be included in the function signature.
2. Functions should be able to return multiple messages, so the return should be a list of messages, which is empty on success.
3. The `tree` and `distinct` functions shouldn't have to be separate. Adapting them might require reworking them substantially, but it's at least worth considering.

**Comment by beckyjackson** [comment]
> Functions should be able to return multiple messages, so the return should be a list of messages, which is empty on success.

Why would we want to return a list of messages rather than a single message? Unless we change this to return a list of dict objects (`{"table": t, "cell": a1, "message": something}`), the message is only added to the cell of the value being checked (and all messages will be combined anyway).

**Comment by jamesaoverton** [comment]
I think that returning a list of messages is fully general, and allows custom functions to do a lot of things.

**Comment by beckyjackson** [comment]
Two improvements to be made (from @jamesaoverton):

1. A simple change is a utility function to generate a message dict from coordinates. So replace this code that shows up dozens of times:

```
        row_start = config["row_start"]
         col_idx = config["table_details"][table]["fields"].index(column)
         return [
             {
                 "table": table,
                 "cell": idx_to_a1(row_idx + row_start, col_idx + 1),
                 "message": "\n".join(errs),
             }
         ]
```

2. The datatype, field, and rule tables are just tables like the rest. It should be possible to validate them like we validate the other tables, by defining their datatypes and fields. e.g. `datatype.level in("ERROR", "WARN", "INFO")`

**Comment by beckyjackson** [comment]
@jamesaoverton I've simplified the returns for a lot of the methods and I think that's helped clean up the code. I'm not quite sure if validating the config tables like the other tables is the best idea - we would need to store the rules somewhere anyway and I think it might end up a little messier.

**Comment by jamesaoverton** [comment]
Ok. My idea might be crazy, but I still want to give it a try. I'll try to make time tomorrow.

**Comment by jamesaoverton** [comment]
I started on a fairly deep refactoring but ran out of time. My goal was to bootstrap more cleanly, and reuse as much machinery as possible to check the required tables: datatype, field, rule. It's working fine so far, but I'll need you to finish.

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
