### PR TITLE
Set up for 0.1.0 release

### PR DESCRIPTION
**Pull request by beckyjackson**
Changes:
* Add GitHub workflows for releasing VALVE
* Change main method to `validate` and move `write_errors` to main as `write_messages`
* Do not `sys.exit(1)` on messages (this breaks our pipelines, but maybe add an option like ROBOT's fail-on at some point)
* Bump to version `0.1.0`

### CODE REVIEW

**Review by jamesaoverton — APPROVED** [review]
Looks good. Please raise an exception on multiple datatype, field, or rule tables. Then merge.

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
I changed my mind -- there's a few things I'd like before merging:

1. `main` should `sys.exit(1)` if there are any ERROR level messages
2. raise an exception on duplicate config tables (datatype, field, rule)
3. I think `build_table_descendants` is not used, and should be removed.
4. `validate` should be able to accept more than just a list of directories. In the future we want to support Excel files, at least. It should also be possible to precisely specify tables without matching file names. Let's talk about how this should work. I think it will just be a matter of reorganization, not much new code.

**Comment by beckyjackson** [comment]
> main should sys.exit(1) if there are any ERROR level messages

I'm worried about this for our workflows. If we `sys.exit(1)` then the make process stops, and we can't apply & push to Google sheets with COGS.

> validate should be able to accept more than just a list of directories.

I've updated it to accept a list of paths OR a config object. In the future we can add support for Excel sheets as well.

**Comment by jamesaoverton** [comment]
GNU Make can always ignore exit codes, by prefixing the line with `-`.

**Comment by beckyjackson** [comment]
OK - I added the `sys.exit(1)`

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
