### PR TITLE
Add optional message to config tables

### PR DESCRIPTION
**Pull request by beckyjackson**
This PR adds support for a `message` column in `field.tsv`. The message will replace the default VALVE error messages, which are sometimes unhelpful. You can include the problematic value in the message by including `{value}` in the message. I will update the main VALVE docs as soon as this is approved.

### CODE REVIEW

**Review by jamesaoverton — APPROVED** [review]
I like it.

**Comment by jamesaoverton** [comment]
Should we do something similar for datatype and rule, or wait?

**Comment by beckyjackson** [comment]
Datatype already has "description", but I think we append this to the error message instead of using it to replace it. If anything, maybe we change "description" to "message" and make it behave like this. I think it would be good to add this to the rule table too, though.

**Comment by jamesaoverton** [comment]
That sounds good to me. We can do it now or later, as you prefer.

**Comment by beckyjackson** [comment]
OK - I've updated both the rule and datatype tables to use the "message" column as well.

**Comment by beckyjackson** [comment]
Ah, we will need to update the integration tests because the output rows changed slightly.

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
