### PR TITLE
First pass at `sub` function, has bugs

### LINKED ISSUE #27: Implement `sub` function for substitutions
I need to validate lists of cell gates for flow cytometry. Most gates consist of a protein name and an expression level,  e.g. "CD4+". I will have a list of protein names, so I can use `in(protein.Synonym)` to match the "CD4" part. But I need to ignore the "+".

So I'm proposing a `sub` function, similar to Python's `re.sub(pattern, match, string)`: `sub(pattern, match, expression)`, e.g. `sub("(\+|-)*$", "", in(protein.Synonym))`.

I wrote a first pass at this, but ran into a bug with the grammar #26.

It might be better if the pattern used slashes instead of quotes, but that would require a change to the grammar. E.g. `sub(/(\+|-)*$/, "", in(protein.Synonym))`.

### PR DESCRIPTION
**Pull request by jamesaoverton**
Fixes #27.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
The changes to `valve/valve/py` should be OKish. The changes the `valve/parse.py` are ugly. I'd like an automated process to update the Python from the Nearley grammar.

**Comment by beckyjackson** [comment]
We have an automated method for transforming the Nearley grammar to `parse.py`, but the manual fixes you made in this PR don't propagate from the Nearley grammar. What works for Nearley to parse empty quotes doesn't work in Python, so we need to make manual changes to the `parse.py` file. I'm not sure what the best solution is; I don't think I can regex replace these bits of code.

**Comment by jamesaoverton** [comment]
Yes, it needs to be fixed in the grammar somehow, but I've been having trouble with it.

**Comment by beckyjackson** [comment]
I can't remember if I wrote this on GitHub yet, but I know I already talked to you about it. I think the easiest workaround is to switch to Perl-style regex for `sub` instead of `pattern, replacement` arguments:
```
sub(s/pattern/replacement/g)
```

I'm working on parsing regex in https://github.com/ontodev/valve.js/pull/6

We don't necessarily need the `valve.js` grammar update I proposed, but it would be nice to parse it with the grammar instead of parsing it with Python later on.

**Comment by jamesaoverton** [comment]
I like your proposal. It doesn't fix the underlying problem, but so far this is the only case where we've needed an empty string.

**Comment by beckyjackson** [comment]
I updated the `valve/parse.py` file based on the new `valve.js` grammar that includes regex parsing. I updated the `sub` function to use this and added test cases from your HIPC validation example, e.g.:

```
sub(s/(\[.*\])?(\+|-)*$//g, in(protein.Synonym))
```

The tests failed with "more than one rule table found" which is weird; they pass locally, so I'll figure out why that happened.

**Comment by beckyjackson** [comment]
OK - it's fixed now

**Comment by jamesaoverton** [comment]
The code looks good. The tests are also good for testing VALVE, but they're ontologically wrong, and I think it would be better to make them right. Please rearrange a few things and then merge:

- rename "cell.tsv" to "cytometry.tsv"
- add a new "cell.tsv" and move the "CD4-positive, alpha-beta T cell" row from "protein.tsv" to "cell.tsv" -- it's a cell type not a protein type
- update "field.tsv" to validate the cell name against `cell.Label` instead of `protein.Label`.

**Pull request merged**
